# Generated by Django 3.2.6 on 2021-09-07 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        ('teachers', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Holiday_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='School_term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Term_Name', models.CharField(max_length=100)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='School_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AC', 'Academic Activity'), ('GS', 'Games & Sports'), ('Cl', 'Clubs Activity'), ('OT', 'Other Activity')], default='AC', max_length=10)),
                ('Event_Name', models.CharField(blank=True, help_text='Second Term Ball Games or National Choir', max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('TripDate', models.DateField()),
                ('TripReturnDate', models.DateField()),
                ('busasigned', models.BooleanField()),
                ('Stundent', models.ManyToManyField(blank=True, to='student.Student_Admission')),
                ('bus', models.ManyToManyField(to='transport.Bus')),
                ('classgoing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.class_room')),
                ('teacher', models.ManyToManyField(to='teachers.Teacher')),
            ],
            options={
                'verbose_name_plural': 'School Activities',
            },
        ),
        migrations.CreateModel(
            name='Half_term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_Activities.school_term')),
            ],
        ),
    ]
