# Generated by Django 3.2.6 on 2021-09-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('Ex', 'Expenses'), ('St', 'Students'), ('Inc', 'Income')], default='Ex', max_length=100)),
                ('Account_Number', models.IntegerField()),
                ('Bank_Name', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Set_School_Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fee_Name', models.CharField(max_length=100)),
                ('Amount', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Add School Fees',
            },
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiontype', models.CharField(max_length=100)),
                ('trans_Date', models.DateField()),
                ('desc', models.TextField(max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='ledger_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'verbose_name_plural': 'Legder Entries',
            },
        ),
    ]
