# Generated by Django 3.2.6 on 2021-09-07 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay_Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.PositiveIntegerField(blank=True)),
                ('Fee_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.set_school_fee')),
            ],
            options={
                'verbose_name_plural': 'Pay School Fees',
            },
        ),
    ]
