# Generated by Django 3.2.6 on 2021-08-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set_School_Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fee_Name', models.CharField(max_length=100)),
                ('Amount', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Add School Fees',
            },
        ),
    ]
