# Generated by Django 3.2.6 on 2021-09-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_pay_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pay_fee',
            options={'verbose_name_plural': 'Pay Fees'},
        ),
    ]
