# Generated by Django 3.2.6 on 2021-09-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Exam Types',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catonemarks', models.IntegerField(default=0, null=True)),
                ('Cattwomarks', models.IntegerField(default=0, null=True)),
                ('Mainmarks', models.IntegerField(default=0, null=True)),
                ('examID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examination.exam')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_admission')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='Exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examination.exam_type'),
        ),
    ]
