# Generated by Django 3.2.6 on 2021-09-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam_result',
            old_name='Catonemarks',
            new_name='Cat_One',
        ),
        migrations.RenameField(
            model_name='exam_result',
            old_name='Cattwomarks',
            new_name='Cat_Two',
        ),
        migrations.RenameField(
            model_name='exam_result',
            old_name='Mainmarks',
            new_name='Main_Marks',
        ),
    ]
