# Generated by Django 3.2.6 on 2021-09-08 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0005_remove_exam_result_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam_result',
            old_name='studentID',
            new_name='Admin_No',
        ),
        migrations.AlterField(
            model_name='exam_result',
            name='Cat_One',
            field=models.IntegerField(default=0, help_text='Cat Mark is 0-30', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='exam_result',
            name='Cat_Two',
            field=models.IntegerField(default=0, help_text='Cat Mark is 0-30', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='exam_result',
            name='Main_Marks',
            field=models.IntegerField(default=0, help_text='Cat Mark is 0-70', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)]),
        ),
    ]
