# Generated by Django 3.2.6 on 2021-08-06 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ENG', 'English'), ('ENGl', 'English Lit'), ('KISW', 'Kiswahili'), ('KISW1', 'Kiswahili Fasihi'), ('MATH', 'Mathematics'), ('Bio', 'Biology'), ('CHEM', 'Chemistry'), ('Geo', 'Geography'), ('HIS', 'History'), ('CRE', 'Christian Religious Education'), ('Agr', 'Agriculture')], default='ENG', max_length=5)),
                ('category', models.CharField(choices=[('s', 'Sciences'), ('L', 'Languages'), ('T', 'Technicals'), ('A', 'Arts'), ('B', 'Business')], default='L', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TSC_Number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=100)),
                ('date_of_birth', models.DateField()),
                ('subject', models.ManyToManyField(blank=True, to='teachers.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Assign_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('Duration', models.IntegerField()),
                ('Role', models.ManyToManyField(blank=True, null=True, to='teachers.TeacherRole')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
    ]
