# Generated by Django 3.2.6 on 2021-09-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_role',
            name='Role',
            field=models.ManyToManyField(blank=True, to='teachers.TeacherRole'),
        ),
    ]
