# Generated by Django 3.2.6 on 2021-09-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_Name', models.CharField(max_length=200)),
                ('Stream_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=100)),
                ('Date_and_Time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Reference Calender',
            },
        ),
        migrations.CreateModel(
            name='Ref_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_Name', models.CharField(max_length=100)),
                ('Day_Number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Reference Days',
            },
        ),
        migrations.CreateModel(
            name='Ref_Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Period_Start_Time', models.TimeField()),
                ('Period_Start_End', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Reference Periods',
            },
        ),
        migrations.CreateModel(
            name='Ref_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Decription', models.CharField(max_length=200)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject')),
            ],
            options={
                'verbose_name_plural': 'Reference Subjects',
            },
        ),
        migrations.CreateModel(
            name='Planned_Timetable',
            fields=[
                ('Schedule_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Day_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetabling.ref_day')),
                ('Period_Number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetabling.ref_period')),
                ('Subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.subject')),
            ],
            options={
                'verbose_name_plural': 'Scheduled Timetables',
            },
        ),
        migrations.CreateModel(
            name='Master_Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_Stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.class_stream')),
                ('Date_Time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetabling.ref_period')),
                ('Day_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetabling.ref_day')),
                ('Schedule_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.planned_timetable')),
                ('Subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.subject')),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher')),
            ],
            options={
                'verbose_name_plural': 'Master Timetable',
            },
        ),
        migrations.CreateModel(
            name='Generated_Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TT_Name', models.CharField(max_length=200)),
                ('Class_Stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.class_stream')),
                ('Day_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetabling.ref_day')),
                ('Schedule_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.planned_timetable')),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher')),
            ],
            options={
                'verbose_name_plural': 'Generated Timetables',
            },
        ),
    ]
