# Generated by Django 3.2.6 on 2021-08-12 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_Name', models.CharField(max_length=200)),
                ('Stream_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='generated_timetable',
            options={'verbose_name_plural': 'Generated Timetables'},
        ),
        migrations.AlterModelOptions(
            name='master_timetable',
            options={'verbose_name_plural': 'Master Timetable'},
        ),
        migrations.AlterModelOptions(
            name='planned_timetable',
            options={'verbose_name_plural': 'Scheduled Timetables'},
        ),
        migrations.AlterModelOptions(
            name='ref_calender',
            options={'verbose_name_plural': 'Referenace Calender'},
        ),
        migrations.AlterModelOptions(
            name='ref_day',
            options={'verbose_name_plural': 'Referenace Days'},
        ),
        migrations.AlterModelOptions(
            name='ref_period',
            options={'verbose_name_plural': 'Reference Periods'},
        ),
        migrations.AlterModelOptions(
            name='ref_subject',
            options={'verbose_name_plural': 'Referenace Subjects'},
        ),
        migrations.AddField(
            model_name='generated_timetable',
            name='Class_Stream',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='timetabling.class_stream'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='master_timetable',
            name='Class_Stream',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='timetabling.class_stream'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ref_period',
            name='Class_Stream',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='timetabling.class_stream'),
            preserve_default=False,
        ),
    ]
