# Generated by Django 3.2.6 on 2021-08-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0002_auto_20210812_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ref_calender',
            options={'verbose_name_plural': 'Reference Calender'},
        ),
        migrations.AlterModelOptions(
            name='ref_day',
            options={'verbose_name_plural': 'Reference Days'},
        ),
        migrations.AlterModelOptions(
            name='ref_subject',
            options={'verbose_name_plural': 'Reference Subjects'},
        ),
        migrations.RenameField(
            model_name='generated_timetable',
            old_name='Period_Number',
            new_name='Time',
        ),
        migrations.RemoveField(
            model_name='ref_period',
            name='Class_Stream',
        ),
    ]
