# Generated by Django 3.2.6 on 2021-08-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0003_auto_20210812_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generated_timetable',
            name='Day_Name',
        ),
        migrations.RemoveField(
            model_name='generated_timetable',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='generated_timetable',
            name='Time',
        ),
        migrations.AddField(
            model_name='generated_timetable',
            name='TT_Name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
