# Generated by Django 3.2.6 on 2021-08-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0004_auto_20210812_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='generated_timetable',
            name='Day_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetabling.ref_day'),
        ),
    ]
