# Generated by Django 3.2.6 on 2021-08-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormetry',
            name='bed_number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dormetry',
            name='cube',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
