# Generated by Django 3.2.6 on 2021-08-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210806_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Att_Date', models.DateField()),
                ('Status', models.BooleanField()),
                ('remark', models.TextField()),
                ('Admin_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_registration')),
            ],
        ),
    ]
