# Generated by Django 3.2.6 on 2021-08-16 19:18

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210816_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='id_card',
            name='Admin_No',
        ),
        migrations.AddField(
            model_name='id_card',
            name='Admin_Number',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='student.student_admission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='id_card',
            name='Student_Name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.fields.related.ForeignKey, to='student.student_registration'),
            preserve_default=False,
        ),
    ]
