# Generated by Django 3.2.6 on 2021-09-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('partner_type', models.CharField(choices=[('AC', 'academic'), ('FA', 'Financial'), ('SG', 'Social Groups')], default='AC', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_of_project', models.CharField(max_length=200)),
                ('start_Date', models.DateField()),
                ('duration', models.IntegerField()),
                ('description', models.TextField(max_length=700)),
                ('budget', models.CharField(max_length=200)),
                ('source_of_funds', models.CharField(max_length=200)),
                ('Project_Status', models.CharField(choices=[('IP', 'in Progress'), ('CP', 'Project Completed'), ('SP', 'Incomplete Stopped'), ('Ab', 'Abandoned'), ('Td', 'Tendering Process')], default='IP', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_of_project', models.CharField(max_length=200)),
                ('start_Date', models.DateField()),
                ('duration', models.IntegerField()),
                ('description', models.TextField(max_length=700)),
                ('budget', models.CharField(max_length=200)),
                ('source_of_funds', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Upcoming Projects',
            },
        ),
    ]
